# Generated by Django 6.0.5 on 2026-05-24 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('process_type', models.CharField(choices=[('procure_to_pay', 'Procure-to-Pay'), ('order_to_cash', 'Order-to-Cash'), ('inventory_fulfillment', 'Inventory Fulfillment'), ('employee_management', 'Employee Management'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
    ]
