# Generated by Django 6.0.5 on 2026-05-24 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employeeinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('system_quality', 'System Quality'), ('information_quality', 'Information Quality'), ('process_efficiency', 'Process Efficiency'), ('user_satisfaction', 'User Satisfaction'), ('perceived_roi', 'Perceived ROI')], max_length=50)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('predefined', 'Predefined'), ('custom', 'Custom')], default='predefined', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
    ]
