# Generated by Django 6.0.5 on 2026-05-24 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_evaluationquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationquestion',
            name='business_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.businessprocess'),
        ),
        migrations.AddField(
            model_name='evaluationquestion',
            name='diagnosis_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluationquestion',
            name='diagnosis_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evaluationquestion',
            name='process_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
