# Generated by Django 6.0.5 on 2026-05-25 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_evaluationquestion_business_process_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('feedback_text', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('business_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.businessprocess')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('employee', 'business_process', 'category')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('business_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.businessprocess')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.evaluationquestion')),
            ],
            options={
                'unique_together': {('employee', 'question')},
            },
        ),
    ]
